### ISSUE TITLE
Installing s3-ocr in a GitHub Actions workflow usually fails to work

### ISSUE THREAD

**Issue by simonw** [simonw/s3-ocr#26]
> Status right now is that `pip install s3-ocr` appears to work fine on an operating system with an older version of Click installed as an OS package already.
>
> But... it doesn't yet install successfully using GitHub Actions, and I cannot figure out why.

_Originally posted by @simonw in https://github.com/simonw/s3-ocr/issues/25#issuecomment-1209819292_

**Comment by simonw** [comment]
Weirdly, using `tmate` to get an interactive debugging shell - https://til.simonwillison.net/github-actions/debug-tmate - and then running `pip install s3-ocr` (for version 0.6.1 or higher) produces a version of `s3-ocr` that works fine.

But when I try to install it from a `requirements.txt` file I'm still seeing the bug from #25 where `s3-ocr --help` fails to list the available commands, presumably because it's running against click 7.0 rather than click 8.0.

**Comment by simonw** [comment]
I'm so confused right now.

Even installing `s3-ocr` directly into a fresh virtual environment isn't working - I'm still getting the same error, where `--help` shows that the commands were not correctly registered!

**Comment by peterjanes** [comment]
Is it possible it's a bug in click 8.0 that was fixed in 8.1? I don't know enough about the package to make sense of [its changelog](https://click.palletsprojects.com/en/8.1.x/changes/) but maybe ["type checking [would] report that a command was not callable"](https://github.com/pallets/click/issues/2227) is it?

**Comment by simonw** [comment]
I used `tmate` to open a `venv/bin/python` shell and ran the following:
```pycon
>>> import pkg_resources
>>> {
...         d.project_name: d.version
...         for d in sorted(pkg_resources.working_set, key=lambda d: d.project_name.lower())
...     }
{'aiofiles': '0.8.0', 'anyio': '3.6.1', 'asgi-csrf': '0.9', 'asgiref': '3.5.2', 'boto3': '1.24.48', 'botocore': '1.27.48', 'certifi': '2022.6.15', 'click': '8.0.4', 'click-default-group': '1.2.2', 'click-default-group-wheel': '1.2.2', 'datasette': '0.61.1', 'datasette-publish-vercel': '0.14.1', 'h11': '0.12.0', 'httpcore': '0.15.0', 'httpx': '0.23.0', 'hupper': '1.10.3', 'idna': '3.3', 'itsdangerous': '2.1.2', 'janus': '1.0.0', 'Jinja2': '3.0.3', 'jmespath': '1.0.1', 'MarkupSafe': '2.1.1', 'mergedeep': '1.3.4', 'Pint': '0.19.2', 'pip': '22.2.1', 'pluggy': '1.0.0', 'python-baseconv': '1.2.2', 'python-dateutil': '2.8.2', 'python-multipart': '0.0.5', 'PyYAML': '6.0', 'rfc3986': '1.5.0', 's3-credentials': '0.12.1', 's3-ocr': '0.6.1', 's3transfer': '0.6.0', 'setuptools': '63.2.0', 'six': '1.16.0', 'sniffio': '1.2.0', 'sqlite-fts4': '1.0.3', 'sqlite-utils': '3.28', 'tabulate': '0.8.10', 'typing-extensions': '4.3.0', 'urllib3': '1.26.11', 'uvicorn': '0.18.2'}
```
In there:

`'click': '8.0.4', 'click-default-group': '1.2.2', 'click-default-group-wheel': '1.2.2'`

So this isn't down to Click 7.0 being installed any more?

**Comment by simonw** [comment]
```pycon
>>> import s3_ocr.cli
>>> s3_ocr.cli.cli.commands
{}
```
It's an empty list, so the commands still are not being registered correctly.

**Comment by simonw** [comment]
In that same `tmate` session I ran:

    runner@fv-az38-793:~/work/sfms-history/sfms-history$ pip install s3-ocr                                                                                 

And now this works:
```
runner@fv-az38-793:~/work/sfms-history/sfms-history$ s3-ocr --help
Usage: s3-ocr [OPTIONS] COMMAND [ARGS]...

  Tools for running OCR against files stored in S3

  Docs: https://github.com/simonw/s3-ocr/blob/main/README.md

  Changelog: https://github.com/simonw/s3-ocr/releases

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  dedupe       Scan every file in the bucket checking for duplicates -...
  fetch        Fetch the OCR results for a specified file
  index        Create a SQLite database with OCR results for files in a...
  inspect-job  Show the current status of an OCR job
  start        Start OCR tasks for PDF files in an S3 bucket
  status       Show status of OCR jobs for a bucket
  text         Retrieve the text from an OCRd PDF file
```
BUT... if I try the same thing in the `venv`:

    venv/bin/pip install s3-ocr
    venv/bin/s3-ocr --help

I get the bug:

```
runner@fv-az38-793:~/work/sfms-history/sfms-history$ venv/bin/s3-ocr --help
Usage: s3-ocr [OPTIONS] COMMAND [ARGS]...

  Tools for running OCR against files stored in S3

  Docs: https://github.com/simonw/s3-ocr/blob/main/README.md

  Changelog: https://github.com/simonw/s3-ocr/releases

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.
```

**Comment by simonw** [comment]
There's something else going on here. Even without caching, and running `pip install s3-ocr` first, and ensuring I get click 8.x, I'm still seeing the bug.

I can't figure out a workaround - and yet when I instead SSH in via `tmate` I can install a working copy of the tool just fine.

**Comment by simonw** [comment]
Just spotted this: https://github.com/simonw/s3-ocr/blob/d107f0c969c4413d6ffee7b63ba37b827393620e/s3_ocr/cli.py#L207-L213

Shouldn't that be `@cli.command()` ?

**Comment by simonw** [comment]
That fixed it!!
